### ISSUE TITLE
Is it working on iOS simulator?

### ISSUE THREAD

**Issue by xcarpentier** [saadqbal/react-native-notification-sounds#1]

**Comment by saadqbal** [comment]
Nope. Unfortunately iOS simulator does not have the notification sounds.

**Comment by xcarpentier** [comment]
Ok, thanks.

I test on Android successfully, this is a good job.

But I can’t build on iOS, followed those steps: 
- rn link
- `pod install`
- manual steps from Xcode for adding lib

I have an issue on .h file: 
`'React/RCTBridge.h' file not found`

**Comment by saadqbal** [comment]
I think this issue is not related to the library? What is your React Native version ? Make sure you have cleaned your build. 

Following the below steps may help

Open terminal
Go to the ios folder
Quit Xcode
run pod install
Open .xcworkspace file.
Clean (cmd + Shift + K) and build (cmd + B) the project.

**Comment by xcarpentier** [comment]
Thank you!
I followed steps, don't see a fix yet. 

My RN Version: `react-native: 0.59.10`
